// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.X.OpenApiClient.Two.Marketplace.Handles;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.X.OpenApiClient.Two.Marketplace
{
    /// <summary>
    /// Builds and executes requests for operations under \2\marketplace
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MarketplaceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The handles property</summary>
        public global::Soenneker.X.OpenApiClient.Two.Marketplace.Handles.HandlesRequestBuilder Handles
        {
            get => new global::Soenneker.X.OpenApiClient.Two.Marketplace.Handles.HandlesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Marketplace.MarketplaceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarketplaceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/marketplace", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Marketplace.MarketplaceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MarketplaceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/marketplace", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
