// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Two.Media.Analytics
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMedia_analyticsFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cta_url_clicks")]
        #pragma warning disable CS1591
        Cta_url_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "cta_watch_clicks")]
        #pragma warning disable CS1591
        Cta_watch_clicks,
        #pragma warning restore CS1591
        [EnumMember(Value = "media_key")]
        #pragma warning disable CS1591
        Media_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "play_from_tap")]
        #pragma warning disable CS1591
        Play_from_tap,
        #pragma warning restore CS1591
        [EnumMember(Value = "playback25")]
        #pragma warning disable CS1591
        Playback25,
        #pragma warning restore CS1591
        [EnumMember(Value = "playback50")]
        #pragma warning disable CS1591
        Playback50,
        #pragma warning restore CS1591
        [EnumMember(Value = "playback75")]
        #pragma warning disable CS1591
        Playback75,
        #pragma warning restore CS1591
        [EnumMember(Value = "playback_complete")]
        #pragma warning disable CS1591
        Playback_complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "playback_start")]
        #pragma warning disable CS1591
        Playback_start,
        #pragma warning restore CS1591
        [EnumMember(Value = "timestamp")]
        #pragma warning disable CS1591
        Timestamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "video_views")]
        #pragma warning disable CS1591
        Video_views,
        #pragma warning restore CS1591
        [EnumMember(Value = "watch_time_ms")]
        #pragma warning disable CS1591
        Watch_time_ms,
        #pragma warning restore CS1591
    }
}
