// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.X.OpenApiClient.Two.Ai_trends.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.X.OpenApiClient.Two.Ai_trends
{
    /// <summary>
    /// Builds and executes requests for operations under \2\ai_trends
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ai_trendsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.X.OpenApiClient.Two.ai_trends.item collection</summary>
        /// <param name="position">The ID of the ai trend.</param>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Two.Ai_trends.Item.Ai_trendsItemRequestBuilder"/></returns>
        public global::Soenneker.X.OpenApiClient.Two.Ai_trends.Item.Ai_trendsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.X.OpenApiClient.Two.Ai_trends.Item.Ai_trendsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Ai_trends.Ai_trendsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ai_trendsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/ai_trends", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Ai_trends.Ai_trendsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Ai_trendsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/ai_trends", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
