// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// Block-level metadata for mentions, hashtags, cashtags, and URLs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArticleDraftCreateRequestContentStateBlocksItemData : IParsable
    {
        /// <summary>Cashtag spans in this block.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataCashtagsItem>? Cashtags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataCashtagsItem> Cashtags { get; set; }
#endif
        /// <summary>Hashtag spans in this block.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataHashtagsItem>? Hashtags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataHashtagsItem> Hashtags { get; set; }
#endif
        /// <summary>Mention spans in this block.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataMentionsItem>? Mentions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataMentionsItem> Mentions { get; set; }
#endif
        /// <summary>URL spans in this block.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataUrlsItem>? Urls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataUrlsItem> Urls { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cashtags", n => { Cashtags = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataCashtagsItem>(global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataCashtagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hashtags", n => { Hashtags = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataHashtagsItem>(global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataHashtagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mentions", n => { Mentions = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataMentionsItem>(global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataMentionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "urls", n => { Urls = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataUrlsItem>(global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataUrlsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataCashtagsItem>("cashtags", Cashtags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataHashtagsItem>("hashtags", Hashtags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataMentionsItem>("mentions", Mentions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.ArticleDraftCreateRequestContentStateBlocksItemDataUrlsItem>("urls", Urls);
        }
    }
}
#pragma warning restore CS0618
