// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>Whether the entity can be edited.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ArticleDraftCreateRequestContentStateEntitiesItemValueMutability
    {
        [EnumMember(Value = "immutable")]
        #pragma warning disable CS1591
        Immutable,
        #pragma warning restore CS1591
        [EnumMember(Value = "mutable")]
        #pragma warning disable CS1591
        Mutable,
        #pragma warning restore CS1591
        [EnumMember(Value = "segmented")]
        #pragma warning disable CS1591
        Segmented,
        #pragma warning restore CS1591
    }
}
