// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BroadcastChatMessageFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "author_id")]
        #pragma warning disable CS1591
        AuthorId,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_name")]
        #pragma warning disable CS1591
        AuthorName,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_username")]
        #pragma warning disable CS1591
        AuthorUsername,
        #pragma warning restore CS1591
        [EnumMember(Value = "broadcast_id")]
        #pragma warning disable CS1591
        BroadcastId,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at_ms")]
        #pragma warning disable CS1591
        CreatedAtMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "reply_to")]
        #pragma warning disable CS1591
        ReplyTo,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
    }
}
