// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BroadcastFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "available_for_replay")]
        #pragma warning disable CS1591
        AvailableForReplay,
        #pragma warning restore CS1591
        [EnumMember(Value = "broadcast_id")]
        #pragma warning disable CS1591
        BroadcastId,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat_option")]
        #pragma warning disable CS1591
        ChatOption,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at_ms")]
        #pragma warning disable CS1591
        CreatedAtMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_ms")]
        #pragma warning disable CS1591
        EndMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "height")]
        #pragma warning disable CS1591
        Height,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_url")]
        #pragma warning disable CS1591
        ImageUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_url_medium")]
        #pragma warning disable CS1591
        ImageUrlMedium,
        #pragma warning restore CS1591
        [EnumMember(Value = "image_url_small")]
        #pragma warning disable CS1591
        ImageUrlSmall,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_high_latency")]
        #pragma warning disable CS1591
        IsHighLatency,
        #pragma warning restore CS1591
        [EnumMember(Value = "language")]
        #pragma warning disable CS1591
        Language,
        #pragma warning restore CS1591
        [EnumMember(Value = "media_key")]
        #pragma warning disable CS1591
        MediaKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "scheduled_end_ms")]
        #pragma warning disable CS1591
        ScheduledEndMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "scheduled_start_ms")]
        #pragma warning disable CS1591
        ScheduledStartMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "share_url")]
        #pragma warning disable CS1591
        ShareUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "source_id")]
        #pragma warning disable CS1591
        SourceId,
        #pragma warning restore CS1591
        [EnumMember(Value = "start_ms")]
        #pragma warning disable CS1591
        StartMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "state")]
        #pragma warning disable CS1591
        State,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_watched")]
        #pragma warning disable CS1591
        TotalWatched,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_watching")]
        #pragma warning disable CS1591
        TotalWatching,
        #pragma warning restore CS1591
        [EnumMember(Value = "tweet_id")]
        #pragma warning disable CS1591
        TweetId,
        #pragma warning restore CS1591
        [EnumMember(Value = "twitter_user_id")]
        #pragma warning disable CS1591
        TwitterUserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at_ms")]
        #pragma warning disable CS1591
        UpdatedAtMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "width")]
        #pragma warning disable CS1591
        Width,
        #pragma warning restore CS1591
    }
}
