// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatConversationFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "admin_settings")]
        #pragma warning disable CS1591
        AdminSettings,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_avatar_url")]
        #pragma warning disable CS1591
        GroupAvatarUrl,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_description")]
        #pragma warning disable CS1591
        GroupDescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_description_key_version")]
        #pragma warning disable CS1591
        GroupDescriptionKeyVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_name")]
        #pragma warning disable CS1591
        GroupName,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite")]
        #pragma warning disable CS1591
        Invite,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_muted")]
        #pragma warning disable CS1591
        IsMuted,
        #pragma warning restore CS1591
        [EnumMember(Value = "message_ttl_ms")]
        #pragma warning disable CS1591
        MessageTtlMs,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_member_ids")]
        #pragma warning disable CS1591
        PendingMemberIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "screen_capture_blocking_enabled")]
        #pragma warning disable CS1591
        ScreenCaptureBlockingEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "screen_capture_detection_enabled")]
        #pragma warning disable CS1591
        ScreenCaptureDetectionEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated_at")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
    }
}
