// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCommunityNotesInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Community Note classification.</summary>
        public global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoClassification? Classification { get; set; }
        /// <summary>Whether the note is a media note.</summary>
        public bool? IsMediaNote { get; set; }
        /// <summary>Tags describing why the Post is misleading.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoMisleadingTagsItem?>? MisleadingTags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoMisleadingTagsItem?> MisleadingTags { get; set; }
#endif
        /// <summary>The text summary of the Community Note (must contain a URL).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>Whether the note cites trustworthy sources.</summary>
        public bool? TrustworthySources { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "classification", n => { Classification = n.GetEnumValue<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoClassification>(); } },
                { "is_media_note", n => { IsMediaNote = n.GetBoolValue(); } },
                { "misleading_tags", n => { MisleadingTags = n.GetCollectionOfEnumValues<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoMisleadingTagsItem>()?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "trustworthy_sources", n => { TrustworthySources = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoClassification>("classification", Classification);
            writer.WriteBoolValue("is_media_note", IsMediaNote);
            writer.WriteCollectionOfEnumValues<global::Soenneker.X.OpenApiClient.Models.CreateCommunityNotesInfoMisleadingTagsItem>("misleading_tags", MisleadingTags);
            writer.WriteStringValue("text", Text);
            writer.WriteBoolValue("trustworthy_sources", TrustworthySources);
        }
    }
}
#pragma warning restore CS0618
