// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePostsMediaCallToActions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The app_install property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsAppInstall? AppInstall { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsAppInstall AppInstall { get; set; }
#endif
        /// <summary>The visit_site property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsVisitSite? VisitSite { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsVisitSite VisitSite { get; set; }
#endif
        /// <summary>The watch_now property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsWatchNow? WatchNow { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsWatchNow WatchNow { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_install", n => { AppInstall = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsAppInstall>(global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsAppInstall.CreateFromDiscriminatorValue); } },
                { "visit_site", n => { VisitSite = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsVisitSite>(global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsVisitSite.CreateFromDiscriminatorValue); } },
                { "watch_now", n => { WatchNow = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsWatchNow>(global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsWatchNow.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsAppInstall>("app_install", AppInstall);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsVisitSite>("visit_site", VisitSite);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.CreatePostsMediaCallToActionsWatchNow>("watch_now", WatchNow);
        }
    }
}
#pragma warning restore CS0618
