// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetChatMessageRequestsInboxTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "you_may_know")]
        #pragma warning disable CS1591
        YouMayKnow,
        #pragma warning restore CS1591
        [EnumMember(Value = "low_quality")]
        #pragma warning disable CS1591
        LowQuality,
        #pragma warning restore CS1591
    }
}
