// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetMediaUploadStatusCommandParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STATUS")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
    }
}
