// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HttpsColonSlashSlashApiTwitterCom2ProblemsInvalidRulesType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "https://api.twitter.com/2/problems/invalid-rules")]
        #pragma warning disable CS1591
        HttpsColonSlashSlashApiTwitterCom2ProblemsInvalidRules,
        #pragma warning restore CS1591
    }
}
