// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum HttpsColonSlashSlashApiXCom2ProblemsRecipientNotMessageableType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "https://api.x.com/2/problems/recipient-not-messageable")]
        #pragma warning disable CS1591
        HttpsColonSlashSlashApiXCom2ProblemsRecipientNotMessageable,
        #pragma warning restore CS1591
    }
}
