// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LikeWithTweetAuthorExpansionsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "attachments.media_keys")]
        #pragma warning disable CS1591
        AttachmentsMediaKeys,
        #pragma warning restore CS1591
        [EnumMember(Value = "liked_tweet_author_id")]
        #pragma warning disable CS1591
        LikedTweetAuthorId,
        #pragma warning restore CS1591
        [EnumMember(Value = "liked_tweet_id")]
        #pragma warning disable CS1591
        LikedTweetId,
        #pragma warning restore CS1591
    }
}
