// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// Nonpublic engagement metrics for the media at the time of the request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaNonPublicMetrics : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of users who started playback (0% quartile) of this video.</summary>
        public long? Playback0Count { get; set; }
        /// <summary>Number of users who completed playback (100% quartile) of this video.</summary>
        public long? Playback100Count { get; set; }
        /// <summary>Number of users who watched at least 25% of this video.</summary>
        public long? Playback25Count { get; set; }
        /// <summary>Number of users who watched at least 50% of this video.</summary>
        public long? Playback50Count { get; set; }
        /// <summary>Number of users who watched at least 75% of this video.</summary>
        public long? Playback75Count { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.MediaNonPublicMetrics"/> and sets the default values.
        /// </summary>
        public MediaNonPublicMetrics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.MediaNonPublicMetrics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.MediaNonPublicMetrics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.MediaNonPublicMetrics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "playback_0_count", n => { Playback0Count = n.GetLongValue(); } },
                { "playback_100_count", n => { Playback100Count = n.GetLongValue(); } },
                { "playback_25_count", n => { Playback25Count = n.GetLongValue(); } },
                { "playback_50_count", n => { Playback50Count = n.GetLongValue(); } },
                { "playback_75_count", n => { Playback75Count = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("playback_0_count", Playback0Count);
            writer.WriteLongValue("playback_100_count", Playback100Count);
            writer.WriteLongValue("playback_25_count", Playback25Count);
            writer.WriteLongValue("playback_50_count", Playback50Count);
            writer.WriteLongValue("playback_75_count", Playback75Count);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
