// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// Per-factor bucket counts for a scoring model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NoteScoringStatusRatingCountsPerModelItemValue : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Helpfulness counts for one rating factor bucket.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNegativeFactorBucketCounts? NegativeFactorBucketCounts { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNegativeFactorBucketCounts NegativeFactorBucketCounts { get; set; }
#endif
        /// <summary>Helpfulness counts for one rating factor bucket.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNeutralFactorBucketCounts? NeutralFactorBucketCounts { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNeutralFactorBucketCounts NeutralFactorBucketCounts { get; set; }
#endif
        /// <summary>Helpfulness counts for one rating factor bucket.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValuePositiveFactorBucketCounts? PositiveFactorBucketCounts { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValuePositiveFactorBucketCounts PositiveFactorBucketCounts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValue"/> and sets the default values.
        /// </summary>
        public NoteScoringStatusRatingCountsPerModelItemValue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "negative_factor_bucket_counts", n => { NegativeFactorBucketCounts = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNegativeFactorBucketCounts>(global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNegativeFactorBucketCounts.CreateFromDiscriminatorValue); } },
                { "neutral_factor_bucket_counts", n => { NeutralFactorBucketCounts = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNeutralFactorBucketCounts>(global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNeutralFactorBucketCounts.CreateFromDiscriminatorValue); } },
                { "positive_factor_bucket_counts", n => { PositiveFactorBucketCounts = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValuePositiveFactorBucketCounts>(global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValuePositiveFactorBucketCounts.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNegativeFactorBucketCounts>("negative_factor_bucket_counts", NegativeFactorBucketCounts);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValueNeutralFactorBucketCounts>("neutral_factor_bucket_counts", NeutralFactorBucketCounts);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.NoteScoringStatusRatingCountsPerModelItemValuePositiveFactorBucketCounts>("positive_factor_bucket_counts", PositiveFactorBucketCounts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
