// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// A list of metadata entities (hashtags, mentions, URLs) found in the Post text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostEntities : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesCashtagsItem>? Cashtags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesCashtagsItem> Cashtags { get; set; }
#endif
        /// <summary>The hashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesHashtagsItem>? Hashtags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesHashtagsItem> Hashtags { get; set; }
#endif
        /// <summary>The mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesMentionsItem>? Mentions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesMentionsItem> Mentions { get; set; }
#endif
        /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesUrlsItem>? Urls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostEntitiesUrlsItem> Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.PostEntities"/> and sets the default values.
        /// </summary>
        public PostEntities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.PostEntities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.PostEntities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.PostEntities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cashtags", n => { Cashtags = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesCashtagsItem>(global::Soenneker.X.OpenApiClient.Models.PostEntitiesCashtagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hashtags", n => { Hashtags = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesHashtagsItem>(global::Soenneker.X.OpenApiClient.Models.PostEntitiesHashtagsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mentions", n => { Mentions = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesMentionsItem>(global::Soenneker.X.OpenApiClient.Models.PostEntitiesMentionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "urls", n => { Urls = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesUrlsItem>(global::Soenneker.X.OpenApiClient.Models.PostEntitiesUrlsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesCashtagsItem>("cashtags", Cashtags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesHashtagsItem>("hashtags", Hashtags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesMentionsItem>("mentions", Mentions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostEntitiesUrlsItem>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
