// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Post : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The article property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostArticleProperty? Article { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostArticleProperty Article { get; set; }
#endif
        /// <summary>Metadata about the long-form Article attached to this Post, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostArticleTitleProperty? ArticleTitle { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostArticleTitleProperty ArticleTitle { get; set; }
#endif
        /// <summary>Specifies the type of attachments (if any) present in this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostAttachments? Attachments { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostAttachments Attachments { get; set; }
#endif
        /// <summary>Unique identifier of the author of this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorId { get; set; }
#nullable restore
#else
        public string AuthorId { get; set; }
#endif
        /// <summary>The card_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardUri { get; set; }
#nullable restore
#else
        public string CardUri { get; set; }
#endif
        /// <summary>The unique identifier of the Community this Post belongs to, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommunityId { get; set; }
#nullable restore
#else
        public string CommunityId { get; set; }
#endif
        /// <summary>Annotations inferred about the Post (domain and entity context).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostContextAnnotationsItem>? ContextAnnotations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostContextAnnotationsItem> ContextAnnotations { get; set; }
#endif
        /// <summary>The ID of the conversation this Post belongs to (matches the root Post&apos;s ID).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>Creation time of the Post.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The inclusive start and exclusive end indices of the displayable content of the Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? DisplayTextRange { get; set; }
#nullable restore
#else
        public List<long?> DisplayTextRange { get; set; }
#endif
        /// <summary>Indicates how much longer (if at all) this Post can be edited.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostEditControls? EditControls { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostEditControls EditControls { get; set; }
#endif
        /// <summary>A list of Post IDs in this Post&apos;s edit history chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EditHistoryPostIds { get; set; }
#nullable restore
#else
        public List<string> EditHistoryPostIds { get; set; }
#endif
        /// <summary>A list of metadata entities (hashtags, mentions, URLs) found in the Post text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostEntities? Entities { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostEntities Entities { get; set; }
#endif
        /// <summary>The location tagged on the Post, if the user provided one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostGeo? Geo { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostGeo Geo { get; set; }
#endif
        /// <summary>Unique identifier of this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Unique identifier of the User this Post is replying to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InReplyToUserId { get; set; }
#nullable restore
#else
        public string InReplyToUserId { get; set; }
#endif
        /// <summary>Language of the Post, if detected by X. Returned as a BCP47 language tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lang { get; set; }
#nullable restore
#else
        public string Lang { get; set; }
#endif
        /// <summary>Community-Notes media matches for this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostMatchedMediaNotesItem>? MatchedMediaNotes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostMatchedMediaNotesItem> MatchedMediaNotes { get; set; }
#endif
        /// <summary>Metadata for media attached to this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostMediaMetadataItem>? MediaMetadata { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostMediaMetadataItem> MediaMetadata { get; set; }
#endif
        /// <summary>Nonpublic engagement metrics for the Post at the time of the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostNonPublicMetricsProperty? NonPublicMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostNonPublicMetricsProperty NonPublicMetrics { get; set; }
#endif
        /// <summary>The full content of the Post, including text beyond 280 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostNotePost? NotePost { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostNotePost NotePost { get; set; }
#endif
        /// <summary>Community-Notes request suggestions for this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostNoteRequestSuggestionsItem>? NoteRequestSuggestions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostNoteRequestSuggestionsItem> NoteRequestSuggestions { get; set; }
#endif
        /// <summary>Organic nonpublic engagement metrics for the Post at the time of the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostOrganicMetricsProperty? OrganicMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostOrganicMetricsProperty OrganicMetrics { get; set; }
#endif
        /// <summary>Indicates if this Post is a paid partnership, i.e. it has been disclosed by the author as containing paid promotion.</summary>
        public bool? PaidPartnership { get; set; }
        /// <summary>Indicates if this Post contains URLs marked as sensitive, for example content suitable for mature audiences.</summary>
        public bool? PossiblySensitive { get; set; }
        /// <summary>Promoted nonpublic engagement metrics for the Post at the time of the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostPromotedMetricsProperty? PromotedMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostPromotedMetricsProperty PromotedMetrics { get; set; }
#endif
        /// <summary>Engagement metrics for the Post at the time of the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostPublicMetrics? PublicMetrics { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostPublicMetrics PublicMetrics { get; set; }
#endif
        /// <summary>A list of Posts this Post refers to. If the Post is a Retweet, Quote or Reply, it includes the referenced Post&apos;s type and ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostReferencedPostsItem>? ReferencedPosts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostReferencedPostsItem> ReferencedPosts { get; set; }
#endif
        /// <summary>Shows who can reply to this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplySettings { get; set; }
#nullable restore
#else
        public string ReplySettings { get; set; }
#endif
        /// <summary>The scopes for this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostScopes? Scopes { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostScopes Scopes { get; set; }
#endif
        /// <summary>The name of the app the user posted from. This is deprecated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>URLs suggested as sources for this Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SuggestedSourceLinks { get; set; }
#nullable restore
#else
        public List<string> SuggestedSourceLinks { get; set; }
#endif
        /// <summary>Suggested source URLs for this Post, each with the number of times it was suggested.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.PostSuggestedSourceLinksWithCountsItem>? SuggestedSourceLinksWithCounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.PostSuggestedSourceLinksWithCountsItem> SuggestedSourceLinksWithCounts { get; set; }
#endif
        /// <summary>The content of the Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>Withholding details for withheld content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.PostWithheld? Withheld { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.PostWithheld Withheld { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.Post"/> and sets the default values.
        /// </summary>
        public Post()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.Post"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.Post CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.Post();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "article", n => { Article = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostArticleProperty>(global::Soenneker.X.OpenApiClient.Models.PostArticleProperty.CreateFromDiscriminatorValue); } },
                { "article_title", n => { ArticleTitle = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostArticleTitleProperty>(global::Soenneker.X.OpenApiClient.Models.PostArticleTitleProperty.CreateFromDiscriminatorValue); } },
                { "attachments", n => { Attachments = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostAttachments>(global::Soenneker.X.OpenApiClient.Models.PostAttachments.CreateFromDiscriminatorValue); } },
                { "author_id", n => { AuthorId = n.GetStringValue(); } },
                { "card_uri", n => { CardUri = n.GetStringValue(); } },
                { "community_id", n => { CommunityId = n.GetStringValue(); } },
                { "context_annotations", n => { ContextAnnotations = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostContextAnnotationsItem>(global::Soenneker.X.OpenApiClient.Models.PostContextAnnotationsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conversation_id", n => { ConversationId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "display_text_range", n => { DisplayTextRange = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "edit_controls", n => { EditControls = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostEditControls>(global::Soenneker.X.OpenApiClient.Models.PostEditControls.CreateFromDiscriminatorValue); } },
                { "edit_history_post_ids", n => { EditHistoryPostIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "entities", n => { Entities = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostEntities>(global::Soenneker.X.OpenApiClient.Models.PostEntities.CreateFromDiscriminatorValue); } },
                { "geo", n => { Geo = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostGeo>(global::Soenneker.X.OpenApiClient.Models.PostGeo.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "in_reply_to_user_id", n => { InReplyToUserId = n.GetStringValue(); } },
                { "lang", n => { Lang = n.GetStringValue(); } },
                { "matched_media_notes", n => { MatchedMediaNotes = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostMatchedMediaNotesItem>(global::Soenneker.X.OpenApiClient.Models.PostMatchedMediaNotesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "media_metadata", n => { MediaMetadata = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostMediaMetadataItem>(global::Soenneker.X.OpenApiClient.Models.PostMediaMetadataItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "non_public_metrics", n => { NonPublicMetrics = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostNonPublicMetricsProperty>(global::Soenneker.X.OpenApiClient.Models.PostNonPublicMetricsProperty.CreateFromDiscriminatorValue); } },
                { "note_post", n => { NotePost = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostNotePost>(global::Soenneker.X.OpenApiClient.Models.PostNotePost.CreateFromDiscriminatorValue); } },
                { "note_request_suggestions", n => { NoteRequestSuggestions = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostNoteRequestSuggestionsItem>(global::Soenneker.X.OpenApiClient.Models.PostNoteRequestSuggestionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "organic_metrics", n => { OrganicMetrics = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostOrganicMetricsProperty>(global::Soenneker.X.OpenApiClient.Models.PostOrganicMetricsProperty.CreateFromDiscriminatorValue); } },
                { "paid_partnership", n => { PaidPartnership = n.GetBoolValue(); } },
                { "possibly_sensitive", n => { PossiblySensitive = n.GetBoolValue(); } },
                { "promoted_metrics", n => { PromotedMetrics = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostPromotedMetricsProperty>(global::Soenneker.X.OpenApiClient.Models.PostPromotedMetricsProperty.CreateFromDiscriminatorValue); } },
                { "public_metrics", n => { PublicMetrics = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostPublicMetrics>(global::Soenneker.X.OpenApiClient.Models.PostPublicMetrics.CreateFromDiscriminatorValue); } },
                { "referenced_posts", n => { ReferencedPosts = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostReferencedPostsItem>(global::Soenneker.X.OpenApiClient.Models.PostReferencedPostsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reply_settings", n => { ReplySettings = n.GetStringValue(); } },
                { "scopes", n => { Scopes = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostScopes>(global::Soenneker.X.OpenApiClient.Models.PostScopes.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "suggested_source_links", n => { SuggestedSourceLinks = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "suggested_source_links_with_counts", n => { SuggestedSourceLinksWithCounts = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostSuggestedSourceLinksWithCountsItem>(global::Soenneker.X.OpenApiClient.Models.PostSuggestedSourceLinksWithCountsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "withheld", n => { Withheld = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.PostWithheld>(global::Soenneker.X.OpenApiClient.Models.PostWithheld.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostArticleProperty>("article", Article);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostArticleTitleProperty>("article_title", ArticleTitle);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostAttachments>("attachments", Attachments);
            writer.WriteStringValue("author_id", AuthorId);
            writer.WriteStringValue("card_uri", CardUri);
            writer.WriteStringValue("community_id", CommunityId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostContextAnnotationsItem>("context_annotations", ContextAnnotations);
            writer.WriteStringValue("conversation_id", ConversationId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfPrimitiveValues<long?>("display_text_range", DisplayTextRange);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostEditControls>("edit_controls", EditControls);
            writer.WriteCollectionOfPrimitiveValues<string>("edit_history_post_ids", EditHistoryPostIds);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostEntities>("entities", Entities);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostGeo>("geo", Geo);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("in_reply_to_user_id", InReplyToUserId);
            writer.WriteStringValue("lang", Lang);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostMatchedMediaNotesItem>("matched_media_notes", MatchedMediaNotes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostMediaMetadataItem>("media_metadata", MediaMetadata);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostNonPublicMetricsProperty>("non_public_metrics", NonPublicMetrics);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostNotePost>("note_post", NotePost);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostNoteRequestSuggestionsItem>("note_request_suggestions", NoteRequestSuggestions);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostOrganicMetricsProperty>("organic_metrics", OrganicMetrics);
            writer.WriteBoolValue("paid_partnership", PaidPartnership);
            writer.WriteBoolValue("possibly_sensitive", PossiblySensitive);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostPromotedMetricsProperty>("promoted_metrics", PromotedMetrics);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostPublicMetrics>("public_metrics", PublicMetrics);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostReferencedPostsItem>("referenced_posts", ReferencedPosts);
            writer.WriteStringValue("reply_settings", ReplySettings);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostScopes>("scopes", Scopes);
            writer.WriteStringValue("source", Source);
            writer.WriteCollectionOfPrimitiveValues<string>("suggested_source_links", SuggestedSourceLinks);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.PostSuggestedSourceLinksWithCountsItem>("suggested_source_links_with_counts", SuggestedSourceLinksWithCounts);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("username", Username);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.PostWithheld>("withheld", Withheld);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
