// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>The media category of media</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PreviewImage_media_key_media_category
    {
        [EnumMember(Value = "TweetImage")]
        #pragma warning disable CS1591
        TweetImage,
        #pragma warning restore CS1591
    }
}
