// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PublicKeyFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "identity_public_key_signature")]
        #pragma warning disable CS1591
        IdentityPublicKeySignature,
        #pragma warning restore CS1591
        [EnumMember(Value = "juicebox_config")]
        #pragma warning disable CS1591
        JuiceboxConfig,
        #pragma warning restore CS1591
        [EnumMember(Value = "public_key")]
        #pragma warning disable CS1591
        PublicKey,
        #pragma warning restore CS1591
        [EnumMember(Value = "public_key_version")]
        #pragma warning disable CS1591
        PublicKeyVersion,
        #pragma warning restore CS1591
        [EnumMember(Value = "signing_public_key")]
        #pragma warning disable CS1591
        SigningPublicKey,
        #pragma warning restore CS1591
    }
}
