// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1"/>, <see cref="global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RulesRequestSummary : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1? RulesRequestSummaryOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1 RulesRequestSummaryOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2? RulesRequestSummaryOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2 RulesRequestSummaryOneOf2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.RulesRequestSummary"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.RulesRequestSummary CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.X.OpenApiClient.Models.RulesRequestSummary();
            if("RulesRequestSummaryOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RulesRequestSummaryOneOf1 = new global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1();
            }
            else if("RulesRequestSummaryOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RulesRequestSummaryOneOf2 = new global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RulesRequestSummaryOneOf1 != null)
            {
                return RulesRequestSummaryOneOf1.GetFieldDeserializers();
            }
            else if(RulesRequestSummaryOneOf2 != null)
            {
                return RulesRequestSummaryOneOf2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(RulesRequestSummaryOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf1>(null, RulesRequestSummaryOneOf1);
            }
            else if(RulesRequestSummaryOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.RulesRequestSummaryOneOf2>(null, RulesRequestSummaryOneOf2);
            }
        }
    }
}
#pragma warning restore CS0618
