// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TrendFieldsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "trend_name")]
        #pragma warning disable CS1591
        TrendName,
        #pragma warning restore CS1591
        [EnumMember(Value = "tweet_count")]
        #pragma warning disable CS1591
        TweetCount,
        #pragma warning restore CS1591
    }
}
