// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TweetExpansionsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "article.cover_media")]
        #pragma warning disable CS1591
        ArticleCoverMedia,
        #pragma warning restore CS1591
        [EnumMember(Value = "article.media_entities")]
        #pragma warning disable CS1591
        ArticleMediaEntities,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments.media_keys")]
        #pragma warning disable CS1591
        AttachmentsMediaKeys,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments.media_source_tweet")]
        #pragma warning disable CS1591
        AttachmentsMediaSourceTweet,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachments.poll_ids")]
        #pragma warning disable CS1591
        AttachmentsPollIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "author_id")]
        #pragma warning disable CS1591
        AuthorId,
        #pragma warning restore CS1591
        [EnumMember(Value = "edit_history_tweet_ids")]
        #pragma warning disable CS1591
        EditHistoryTweetIds,
        #pragma warning restore CS1591
        [EnumMember(Value = "entities.mentions.username")]
        #pragma warning disable CS1591
        EntitiesMentionsUsername,
        #pragma warning restore CS1591
        [EnumMember(Value = "geo.place_id")]
        #pragma warning disable CS1591
        GeoPlaceId,
        #pragma warning restore CS1591
        [EnumMember(Value = "in_reply_to_user_id")]
        #pragma warning disable CS1591
        InReplyToUserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "entities.note.mentions.username")]
        #pragma warning disable CS1591
        EntitiesNoteMentionsUsername,
        #pragma warning restore CS1591
        [EnumMember(Value = "referenced_tweets.id")]
        #pragma warning disable CS1591
        ReferencedTweetsId,
        #pragma warning restore CS1591
        [EnumMember(Value = "referenced_tweets.id.attachments.media_keys")]
        #pragma warning disable CS1591
        ReferencedTweetsIdAttachmentsMediaKeys,
        #pragma warning restore CS1591
        [EnumMember(Value = "referenced_tweets.id.author_id")]
        #pragma warning disable CS1591
        ReferencedTweetsIdAuthorId,
        #pragma warning restore CS1591
    }
}
