// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TweetReferencedTweetsItemType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "retweeted")]
        #pragma warning disable CS1591
        Retweeted,
        #pragma warning restore CS1591
        [EnumMember(Value = "quoted")]
        #pragma warning disable CS1591
        Quoted,
        #pragma warning restore CS1591
        [EnumMember(Value = "replied_to")]
        #pragma warning disable CS1591
        RepliedTo,
        #pragma warning restore CS1591
    }
}
