// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// App Install CTA. At least one store id should be provided.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TweetCreateRequest_media_call_to_actions_app_install : IParsable
    {
        /// <summary>Apple App Store iPhone app id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppStoreId { get; set; }
#nullable restore
#else
        public string AppStoreId { get; set; }
#endif
        /// <summary>Apple App Store iPad app id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpadAppStoreId { get; set; }
#nullable restore
#else
        public string IpadAppStoreId { get; set; }
#endif
        /// <summary>Google Play Store app id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlayStoreId { get; set; }
#nullable restore
#else
        public string PlayStoreId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.TweetCreateRequest_media_call_to_actions_app_install"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.TweetCreateRequest_media_call_to_actions_app_install CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.TweetCreateRequest_media_call_to_actions_app_install();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_store_id", n => { AppStoreId = n.GetStringValue(); } },
                { "ipad_app_store_id", n => { IpadAppStoreId = n.GetStringValue(); } },
                { "play_store_id", n => { PlayStoreId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_store_id", AppStoreId);
            writer.WriteStringValue("ipad_app_store_id", IpadAppStoreId);
            writer.WriteStringValue("play_store_id", PlayStoreId);
        }
    }
}
#pragma warning restore CS0618
