// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateChatGroupRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Cryptographic signatures for the action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupActionSignatures>? ActionSignatures { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupActionSignatures> ActionSignatures { get; set; }
#endif
        /// <summary>Base64-encoded key rotation payload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Base64EncodedKeyRotation { get; set; }
#nullable restore
#else
        public string Base64EncodedKeyRotation { get; set; }
#endif
        /// <summary>Version of the conversation key the values are encrypted with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationKeyVersion { get; set; }
#nullable restore
#else
        public string ConversationKeyVersion { get; set; }
#endif
        /// <summary>Encrypted conversation keys for each participant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupConversationParticipantKeys>? ConversationParticipantKeys { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupConversationParticipantKeys> ConversationParticipantKeys { get; set; }
#endif
        /// <summary>Encrypted group avatar URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupAvatarUrl { get; set; }
#nullable restore
#else
        public string GroupAvatarUrl { get; set; }
#endif
        /// <summary>Encrypted group description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupDescription { get; set; }
#nullable restore
#else
        public string GroupDescription { get; set; }
#endif
        /// <summary>Encrypted group name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The group values this request changes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequestModifiedFieldsItem?>? ModifiedFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequestModifiedFieldsItem?> ModifiedFields { get; set; }
#endif
        /// <summary>Message keys re-encrypted with the rotated conversation key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRotatedPmkBundle>? RotatedPmkBundle { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRotatedPmkBundle> RotatedPmkBundle { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_signatures", n => { ActionSignatures = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupActionSignatures>(global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupActionSignatures.CreateFromDiscriminatorValue)?.AsList(); } },
                { "base64_encoded_key_rotation", n => { Base64EncodedKeyRotation = n.GetStringValue(); } },
                { "conversation_key_version", n => { ConversationKeyVersion = n.GetStringValue(); } },
                { "conversation_participant_keys", n => { ConversationParticipantKeys = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupConversationParticipantKeys>(global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupConversationParticipantKeys.CreateFromDiscriminatorValue)?.AsList(); } },
                { "group_avatar_url", n => { GroupAvatarUrl = n.GetStringValue(); } },
                { "group_description", n => { GroupDescription = n.GetStringValue(); } },
                { "group_name", n => { GroupName = n.GetStringValue(); } },
                { "modified_fields", n => { ModifiedFields = n.GetCollectionOfEnumValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequestModifiedFieldsItem>()?.AsList(); } },
                { "rotated_pmk_bundle", n => { RotatedPmkBundle = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRotatedPmkBundle>(global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRotatedPmkBundle.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupActionSignatures>("action_signatures", ActionSignatures);
            writer.WriteStringValue("base64_encoded_key_rotation", Base64EncodedKeyRotation);
            writer.WriteStringValue("conversation_key_version", ConversationKeyVersion);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupConversationParticipantKeys>("conversation_participant_keys", ConversationParticipantKeys);
            writer.WriteStringValue("group_avatar_url", GroupAvatarUrl);
            writer.WriteStringValue("group_description", GroupDescription);
            writer.WriteStringValue("group_name", GroupName);
            writer.WriteCollectionOfEnumValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRequestModifiedFieldsItem>("modified_fields", ModifiedFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UpdateChatGroupRotatedPmkBundle>("rotated_pmk_bundle", RotatedPmkBundle);
        }
    }
}
#pragma warning restore CS0618
