// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// At least one of `allow_dms_from`, `always_allow_dms_from_subscribers`, `dm_quality_filter`, `dm_receipt_settings`, `av_settings` is required.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateChatSettingsRequest : IParsable
    {
        /// <summary>Who can send the user messages: `all` (anyone), `verified` (verified accounts only), or `following` (accounts the user follows).</summary>
        public global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestAllowDmsFrom? AllowDmsFrom { get; set; }
        /// <summary>Whether the user&apos;s subscribers can always message them regardless of allow_dms_from.</summary>
        public bool? AlwaysAllowDmsFromSubscribers { get; set; }
        /// <summary>The av_settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsAvSettings? AvSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsAvSettings AvSettings { get; set; }
#endif
        /// <summary>Low-quality message request filter: `enabled` (low-quality requests go to a separate folder) or `disabled` (all requests stay in the main inbox).</summary>
        public global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmQualityFilter? DmQualityFilter { get; set; }
        /// <summary>Read receipts: `all_enabled` (send and receive read receipts) or `all_disabled` (neither).</summary>
        public global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmReceiptSettings? DmReceiptSettings { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_dms_from", n => { AllowDmsFrom = n.GetEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestAllowDmsFrom>(); } },
                { "always_allow_dms_from_subscribers", n => { AlwaysAllowDmsFromSubscribers = n.GetBoolValue(); } },
                { "av_settings", n => { AvSettings = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsAvSettings>(global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsAvSettings.CreateFromDiscriminatorValue); } },
                { "dm_quality_filter", n => { DmQualityFilter = n.GetEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmQualityFilter>(); } },
                { "dm_receipt_settings", n => { DmReceiptSettings = n.GetEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmReceiptSettings>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestAllowDmsFrom>("allow_dms_from", AllowDmsFrom);
            writer.WriteBoolValue("always_allow_dms_from_subscribers", AlwaysAllowDmsFromSubscribers);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsAvSettings>("av_settings", AvSettings);
            writer.WriteEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmQualityFilter>("dm_quality_filter", DmQualityFilter);
            writer.WriteEnumValue<global::Soenneker.X.OpenApiClient.Models.UpdateChatSettingsRequestDmReceiptSettings>("dm_receipt_settings", DmReceiptSettings);
        }
    }
}
#pragma warning restore CS0618
