// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// A URL entity found in profile text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserEntitiesUrlUrlsItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description of the linked page, when available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The URL as displayed in the Post text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayUrl { get; set; }
#nullable restore
#else
        public string DisplayUrl { get; set; }
#endif
        /// <summary>The end property</summary>
        public long? End { get; set; }
        /// <summary>The fully resolved URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpandedUrl { get; set; }
#nullable restore
#else
        public string ExpandedUrl { get; set; }
#endif
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItemImagesItem>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItemImagesItem> Images { get; set; }
#endif
        /// <summary>The media_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaKey { get; set; }
#nullable restore
#else
        public string MediaKey { get; set; }
#endif
        /// <summary>The start property</summary>
        public long? Start { get; set; }
        /// <summary>HTTP status from resolving the URL.</summary>
        public long? Status { get; set; }
        /// <summary>Title of the linked page, when available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The final destination after following redirects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnwoundUrl { get; set; }
#nullable restore
#else
        public string UnwoundUrl { get; set; }
#endif
        /// <summary>The t.co shortened URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItem"/> and sets the default values.
        /// </summary>
        public UserEntitiesUrlUrlsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "display_url", n => { DisplayUrl = n.GetStringValue(); } },
                { "end", n => { End = n.GetLongValue(); } },
                { "expanded_url", n => { ExpandedUrl = n.GetStringValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItemImagesItem>(global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItemImagesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "media_key", n => { MediaKey = n.GetStringValue(); } },
                { "start", n => { Start = n.GetLongValue(); } },
                { "status", n => { Status = n.GetLongValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "unwound_url", n => { UnwoundUrl = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("display_url", DisplayUrl);
            writer.WriteLongValue("end", End);
            writer.WriteStringValue("expanded_url", ExpandedUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.X.OpenApiClient.Models.UserEntitiesUrlUrlsItemImagesItem>("images", Images);
            writer.WriteStringValue("media_key", MediaKey);
            writer.WriteLongValue("start", Start);
            writer.WriteLongValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("unwound_url", UnwoundUrl);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
