// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.X.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written
{
    /// <summary>
    /// Builds and executes requests for operations under \2\notes\search\notes_written
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Notes_writtenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Notes_writtenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/notes/search/notes_written?test_mode={test_mode}{&max_results*,note%2Efields,pagination_token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Notes_writtenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/notes/search/notes_written?test_mode={test_mode}{&max_results*,note%2Efields,pagination_token*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns all the community notes written by the user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.Get2NotesSearchNotesWrittenResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.X.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.X.OpenApiClient.Models.Get2NotesSearchNotesWrittenResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder.Notes_writtenRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.X.OpenApiClient.Models.Get2NotesSearchNotesWrittenResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder.Notes_writtenRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.X.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.X.OpenApiClient.Models.Get2NotesSearchNotesWrittenResponse>(requestInfo, global::Soenneker.X.OpenApiClient.Models.Get2NotesSearchNotesWrittenResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns all the community notes written by the user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder.Notes_writtenRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder.Notes_writtenRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.Notes_writtenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns all the community notes written by the user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Notes_writtenRequestBuilderGetQueryParameters 
        {
            /// <summary>Max results to return.</summary>
            [QueryParameter("max_results")]
            public int? MaxResults { get; set; }
            /// <summary>A comma separated list of Note fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("note%2Efields")]
            public global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.GetNoteFieldsQueryParameterType[]? NoteFields { get; set; }
#nullable restore
#else
            [QueryParameter("note%2Efields")]
            public global::Soenneker.X.OpenApiClient.Two.Notes.Search.Notes_written.GetNoteFieldsQueryParameterType[] NoteFields { get; set; }
#endif
            /// <summary>Pagination token to get next set of posts eligible for notes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination_token")]
            public string? PaginationToken { get; set; }
#nullable restore
#else
            [QueryParameter("pagination_token")]
            public string PaginationToken { get; set; }
#endif
            /// <summary>If true, return the notes the caller wrote for the test. If false, return the notes the caller wrote on the product.</summary>
            [QueryParameter("test_mode")]
            public bool? TestMode { get; set; }
        }
    }
}
#pragma warning restore CS0618
