// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Two.Compliance.Jobs.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCompliance_jobFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "download_expires_at")]
        #pragma warning disable CS1591
        Download_expires_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "download_url")]
        #pragma warning disable CS1591
        Download_url,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "resumable")]
        #pragma warning disable CS1591
        Resumable,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "type")]
        #pragma warning disable CS1591
        Type,
        #pragma warning restore CS1591
        [EnumMember(Value = "upload_expires_at")]
        #pragma warning disable CS1591
        Upload_expires_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "upload_url")]
        #pragma warning disable CS1591
        Upload_url,
        #pragma warning restore CS1591
    }
}
