// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.X.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent
{
    /// <summary>
    /// Builds and executes requests for operations under \2\tweets\counts\recent
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/counts/recent?query={query}{&end_time*,granularity*,next_token*,pagination_token*,search_count%2Efields,since_id*,start_time*,until_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/counts/recent?query={query}{&end_time*,granularity*,next_token*,pagination_token*,search_count%2Efields,since_id*,start_time*,until_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves the count of Posts from the last 7 days matching a search query.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.Get2TweetsCountsRecentResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.X.OpenApiClient.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.X.OpenApiClient.Models.Get2TweetsCountsRecentResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder.RecentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.X.OpenApiClient.Models.Get2TweetsCountsRecentResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder.RecentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.X.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.X.OpenApiClient.Models.Get2TweetsCountsRecentResponse>(requestInfo, global::Soenneker.X.OpenApiClient.Models.Get2TweetsCountsRecentResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the count of Posts from the last 7 days matching a search query.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder.RecentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder.RecentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves the count of Posts from the last 7 days matching a search query.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecentRequestBuilderGetQueryParameters 
        {
            /// <summary>YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Posts will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute).</summary>
            [QueryParameter("end_time")]
            public DateTimeOffset? EndTime { get; set; }
            /// <summary>The granularity for the search counts results.</summary>
            [Obsolete("This property is deprecated, use GranularityAsGetGranularityQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("granularity")]
            public string? Granularity { get; set; }
#nullable restore
#else
            [QueryParameter("granularity")]
            public string Granularity { get; set; }
#endif
            /// <summary>The granularity for the search counts results.</summary>
            [QueryParameter("granularity")]
            public global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.GetGranularityQueryParameterType? GranularityAsGetGranularityQueryParameterType { get; set; }
            /// <summary>This parameter is used to get the next &apos;page&apos; of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("next_token")]
            public string? NextToken { get; set; }
#nullable restore
#else
            [QueryParameter("next_token")]
            public string NextToken { get; set; }
#endif
            /// <summary>This parameter is used to get the next &apos;page&apos; of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagination_token")]
            public string? PaginationToken { get; set; }
#nullable restore
#else
            [QueryParameter("pagination_token")]
            public string PaginationToken { get; set; }
#endif
            /// <summary>One query/rule/filter for matching Posts. Refer to https://t.co/rulelength to identify the max query length.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>A comma separated list of SearchCount fields to display.</summary>
            [Obsolete("This property is deprecated, use SearchCountFieldsAsGetSearchCountFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search_count%2Efields")]
            public string[]? SearchCountFields { get; set; }
#nullable restore
#else
            [QueryParameter("search_count%2Efields")]
            public string[] SearchCountFields { get; set; }
#endif
            /// <summary>A comma separated list of SearchCount fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search_count%2Efields")]
            public global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.GetSearch_countFieldsQueryParameterType[]? SearchCountFieldsAsGetSearchCountFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("search_count%2Efields")]
            public global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.GetSearch_countFieldsQueryParameterType[] SearchCountFieldsAsGetSearchCountFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Returns results with a Post ID greater than (that is, more recent than) the specified ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("since_id")]
            public string? SinceId { get; set; }
#nullable restore
#else
            [QueryParameter("since_id")]
            public string SinceId { get; set; }
#endif
            /// <summary>YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp (from most recent 7 days) from which the Posts will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute).</summary>
            [QueryParameter("start_time")]
            public DateTimeOffset? StartTime { get; set; }
            /// <summary>Returns results with a Post ID less than (that is, older than) the specified ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("until_id")]
            public string? UntilId { get; set; }
#nullable restore
#else
            [QueryParameter("until_id")]
            public string UntilId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.X.OpenApiClient.Two.Tweets.Counts.Recent.RecentRequestBuilder.RecentRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
