// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.X.OpenApiClient.Two.Chat.Media.Item;
using Soenneker.X.OpenApiClient.Two.Chat.Media.Upload;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.X.OpenApiClient.Two.Chat.Media
{
    /// <summary>
    /// Builds and executes requests for operations under \2\chat\media
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The upload property</summary>
        public global::Soenneker.X.OpenApiClient.Two.Chat.Media.Upload.UploadRequestBuilder Upload
        {
            get => new global::Soenneker.X.OpenApiClient.Two.Chat.Media.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.X.OpenApiClient.Two.chat.media.item collection</summary>
        /// <param name="position">The Chat conversation ID.</param>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Two.Chat.Media.Item.WithConversation_ItemRequestBuilder"/></returns>
        public global::Soenneker.X.OpenApiClient.Two.Chat.Media.Item.WithConversation_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("conversation_id", position);
                return new global::Soenneker.X.OpenApiClient.Two.Chat.Media.Item.WithConversation_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Chat.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Two.Chat.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/chat/media", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
