// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Two.Communities.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCommunityFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "access")]
        #pragma warning disable CS1591
        Access,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "join_policy")]
        #pragma warning disable CS1591
        Join_policy,
        #pragma warning restore CS1591
        [EnumMember(Value = "member_count")]
        #pragma warning disable CS1591
        Member_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
    }
}
