// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Two.Users.Personalized_trends
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPersonalized_trendFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "category")]
        #pragma warning disable CS1591
        Category,
        #pragma warning restore CS1591
        [EnumMember(Value = "post_count")]
        #pragma warning disable CS1591
        Post_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "trend_name")]
        #pragma warning disable CS1591
        Trend_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "trending_since")]
        #pragma warning disable CS1591
        Trending_since,
        #pragma warning restore CS1591
    }
}
