// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Two.Notes.Search.Posts_eligible_for_notes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPollFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "duration_minutes")]
        #pragma warning disable CS1591
        Duration_minutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_datetime")]
        #pragma warning disable CS1591
        End_datetime,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "options")]
        #pragma warning disable CS1591
        Options,
        #pragma warning restore CS1591
        [EnumMember(Value = "voting_status")]
        #pragma warning disable CS1591
        Voting_status,
        #pragma warning restore CS1591
    }
}
