// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActivityStreamingResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The event_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>The unique identifier of an Activity event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventUuid { get; set; }
#nullable restore
#else
        public string EventUuid { get; set; }
#endif
        /// <summary>An XAA subscription.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.ActivitySubscriptionFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.ActivitySubscriptionFilter Filter { get; set; }
#endif
        /// <summary>The payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data_payload? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data_payload Payload { get; set; }
#endif
        /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data"/> and sets the default values.
        /// </summary>
        public ActivityStreamingResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "event_type", n => { EventType = n.GetStringValue(); } },
                { "event_uuid", n => { EventUuid = n.GetStringValue(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.ActivitySubscriptionFilter>(global::Soenneker.X.OpenApiClient.Models.ActivitySubscriptionFilter.CreateFromDiscriminatorValue); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data_payload>(global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data_payload.CreateFromDiscriminatorValue); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("event_type", EventType);
            writer.WriteStringValue("event_uuid", EventUuid);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.ActivitySubscriptionFilter>("filter", Filter);
            writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.ActivityStreamingResponse_data_payload>("payload", Payload);
            writer.WriteStringValue("tag", Tag);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
