// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1"/>, <see cref="global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaUploadAppendRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1? MediaUploadAppendRequestMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1 MediaUploadAppendRequestMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2? MediaUploadAppendRequestMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2 MediaUploadAppendRequestMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequest();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MediaUploadAppendRequestMember1 = new global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MediaUploadAppendRequestMember2 = new global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MediaUploadAppendRequestMember1 != null)
            {
                return MediaUploadAppendRequestMember1.GetFieldDeserializers();
            }
            else if(MediaUploadAppendRequestMember2 != null)
            {
                return MediaUploadAppendRequestMember2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(MediaUploadAppendRequestMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember1>(null, MediaUploadAppendRequestMember1);
            }
            else if(MediaUploadAppendRequestMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.X.OpenApiClient.Models.MediaUploadAppendRequestMember2>(null, MediaUploadAppendRequestMember2);
            }
        }
    }
}
#pragma warning restore CS0618
