// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ResourceUnauthorizedProblem_resource_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "tweet")]
        #pragma warning disable CS1591
        Tweet,
        #pragma warning restore CS1591
        [EnumMember(Value = "media")]
        #pragma warning disable CS1591
        Media,
        #pragma warning restore CS1591
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
        [EnumMember(Value = "space")]
        #pragma warning disable CS1591
        Space,
        #pragma warning restore CS1591
    }
}
