// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.X.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UsageCapExceededProblem_period
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "Monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
    }
}
